package com.anpe.coolbbsyou.net.model.topic

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

@JsonClass(generateAdapter = true)
data class Data(
    @Json(name = "ad_link_url")
    val adLinkUrl: String = "",
    @Json(name = "ad_pic_url")
    val adPicUrl: String = "",
    @Json(name = "admin_uid")
    val adminUid: Int = 0,
    @Json(name = "admin_username")
    val adminUsername: String = "",
    @Json(name = "allow_rate")
    val allowRate: Int = 0,
    @Json(name = "bind_avatar_plugin_id")
    val bindAvatarPluginId: Int = 0,
    @Json(name = "bind_avatar_plugin_keywords")
    val bindAvatarPluginKeywords: String = "",
    @Json(name = "bind_goods_id")
    val bindGoodsId: Int = 0,
    @Json(name = "bind_product_id")
    val bindProductId: Int = 0,
    @Json(name = "click")
    val click: Int = 0,
    @Json(name = "commentnum")
    val commentnum: Int = 0,
    @Json(name = "commentnum_txt")
    val commentnumTxt: String = "",
    @Json(name = "cover")
    val cover: String = "",
    @Json(name = "dateline")
    val dateline: Int = 0,
    @Json(name = "description")
    val description: String = "",
    @Json(name = "disallow_headline")
    val disallowHeadline: Int = 0,
    @Json(name = "entityId")
    val entityId: Int = 0,
    @Json(name = "entityType")
    val entityType: String = "",
    @Json(name = "follownum")
    val follownum: Int = 0,
    @Json(name = "follownum_txt")
    val follownumTxt: String = "",
    @Json(name = "hash")
    val hash: String = "",
    @Json(name = "hot_num")
    val hotNum: Int = 0,
    @Json(name = "hot_num_txt")
    val hotNumTxt: String = "",
    @Json(name = "id")
    val id: Int = 0,
    @Json(name = "intro")
    val intro: String = "",
    @Json(name = "is_live")
    val isLive: Int = 0,
    @Json(name = "is_recommend")
    val isRecommend: Int = 0,
    @Json(name = "keywords")
    val keywords: String = "",
    @Json(name = "lastupdate")
    val lastupdate: Int = 0,
    @Json(name = "level_limit")
    val levelLimit: Int = 0,
    @Json(name = "link_goods_list")
    val linkGoodsList: String = "",
    @Json(name = "link_goods_list_title")
    val linkGoodsListTitle: String = "",
    @Json(name = "live_end_at")
    val liveEndAt: Int = 0,
    @Json(name = "livePresenterNames")
    val livePresenterNames: String = "",
    @Json(name = "live_start_at")
    val liveStartAt: Int = 0,
    @Json(name = "live_status")
    val liveStatus: Int = 0,
    @Json(name = "logo")
    val logo: String = "",
    @Json(name = "only_self_keywords")
    val onlySelfKeywords: String = "",
    @Json(name = "open_rate")
    val openRate: Int = 0,
    @Json(name = "phone_info")
    val phoneInfo: String = "",
    @Json(name = "phone_price")
    val phonePrice: String = "",
    @Json(name = "product_title")
    val productTitle: String = "",
    @Json(name = "publish_limit")
    val publishLimit: Int = 0,
    @Json(name = "rating_average_score")
    val ratingAverageScore: String = "",
    @Json(name = "rating_total_num")
    val ratingTotalNum: Int = 0,
    @Json(name = "recent_follow_list")
    val recentFollowList: List<RecentFollow> = listOf(),
    @Json(name = "recommendRows")
    val recommendRows: List<RecommendRow> = listOf(),
    @Json(name = "relation_tag")
    val relationTag: String = "",
    @Json(name = "replynum")
    val replynum: Int = 0,
    @Json(name = "selectedTab")
    val selectedTab: String = "",
    @Json(name = "show_date")
    val showDate: String = "",
    @Json(name = "simple_rating")
    val simpleRating: Int = 0,
    @Json(name = "sort")
    val sort: Int = 0,
    @Json(name = "star_1_count")
    val star1Count: Int = 0,
    @Json(name = "star_2_count")
    val star2Count: Int = 0,
    @Json(name = "star_3_count")
    val star3Count: Int = 0,
    @Json(name = "star_4_count")
    val star4Count: Int = 0,
    @Json(name = "star_5_count")
    val star5Count: Int = 0,
    @Json(name = "star_average_score")
    val starAverageScore: String = "",
    @Json(name = "star_total_count")
    val starTotalCount: Int = 0,
    @Json(name = "status")
    val status: Int = 0,
    @Json(name = "tabList")
    val tabList: List<Tab> = listOf(),
    @Json(name = "tag_category")
    val tagCategory: String = "",
    @Json(name = "tag_pics")
//    val tagPics: List<String> = listOf(),
    val tagPics: String = "",
    @Json(name = "tag_type")
    val tagType: Int = 0,
    @Json(name = "title")
    val title: String = "",
    @Json(name = "top_feed_id")
    val topFeedId: Int = 0,
    @Json(name = "top_ids")
    val topIds: List<Any> = listOf(),
    @Json(name = "uid")
    val uid: Int = 0,
    @Json(name = "url")
    val url: String = "",
    @Json(name = "userAction")
    val userAction: UserAction = UserAction(),
    @Json(name = "username")
    val username: String = "",
    @Json(name = "video_url")
    val videoUrl: String = "",
    @Json(name = "votenum")
    val votenum: Int = 0,
    @Json(name = "votenum1")
    val votenum1: Int = 0,
    @Json(name = "votenum2")
    val votenum2: Int = 0,
    @Json(name = "votenum3")
    val votenum3: Int = 0,
    @Json(name = "votenum4")
    val votenum4: Int = 0,
    @Json(name = "votenum5")
    val votenum5: Int = 0,
    @Json(name = "votescore")
    val votescore: Int = 0
)