package com.anpe.coolbbsyou.net.model.suggest

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

@JsonClass(generateAdapter = true)
data class Data(
    @Json(name = "adminscore")
    val adminscore: String = "",
    @Json(name = "allow_rating")
    val allowRating: Int = 0,
    @Json(name = "apkRomVersion")
    val apkRomVersion: String = "",
    @Json(name = "apkTypeName")
    val apkTypeName: String = "",
    @Json(name = "apkTypeUrl")
    val apkTypeUrl: String = "",
    @Json(name = "apkUrl")
    val apkUrl: String = "",
    @Json(name = "apklength")
    val apklength: String = "",
    @Json(name = "apkmd5")
    val apkmd5: String = "",
    @Json(name = "apkname")
    val apkname: String = "",
    @Json(name = "apkname2")
    val apkname2: String = "",
    @Json(name = "apksize")
    val apksize: String = "",
    @Json(name = "apktype")
    val apktype: Int = 0,
    @Json(name = "apkversioncode")
    val apkversioncode: Int = 0,
    @Json(name = "apkversionname")
    val apkversionname: String = "",
    @Json(name = "catDir")
    val catDir: String = "",
    @Json(name = "catName")
    val catName: String = "",
    @Json(name = "catid")
    val catid: Int = 0,
    @Json(name = "changelog")
    val changelog: String = "",
    @Json(name = "comment_block_num")
    val commentBlockNum: Int = 0,
    @Json(name = "commentCount")
    val commentCount: String = "",
    @Json(name = "comment_status")
    val commentStatus: Int = 0,
    @Json(name = "commentStatusText")
    val commentStatusText: String = "",
    @Json(name = "commentnum")
    val commentnum: Int = 0,
    @Json(name = "cover")
    val cover: String = "",
    @Json(name = "description")
    val description: String = "",
    @Json(name = "developername")
    val developername: String = "",
    @Json(name = "developeruid")
    val developeruid: Int = 0,
    @Json(name = "digest")
    val digest: Int = 0,
    @Json(name = "downCount")
    val downCount: String = "",
    @Json(name = "downnum")
    val downnum: Int = 0,
    @Json(name = "entityId")
    val entityId: Int = 0,
    @Json(name = "entityTemplate")
    val entityTemplate: String = "",
    @Json(name = "entityType")
    val entityType: String = "",
    @Json(name = "extraFlag")
    val extraFlag: String = "",
    @Json(name = "favnum")
    val favnum: Int = 0,
    @Json(name = "followCount")
    val followCount: String = "",
    @Json(name = "follownum")
    val follownum: Int = 0,
    @Json(name = "get_timewit_cpc")
    val getTimewitCpc: Int = 0,
    @Json(name = "hot_num")
    val hotNum: Int = 0,
    @Json(name = "hot_num_txt")
    val hotNumTxt: String = "",
    @Json(name = "hotlabel")
    val hotlabel: String = "",
    @Json(name = "id")
    val id: Int = 0,
    @Json(name = "index_name")
    val indexName: String = "",
    @Json(name = "is_coolapk_cpa")
    val isCoolapkCpa: Int = 0,
    @Json(name = "is_forum_app")
    val isForumApp: Int = 0,
    @Json(name = "isbiz")
    val isbiz: Int = 0,
    @Json(name = "iscps")
    val iscps: Int = 0,
    @Json(name = "ishot")
    val ishot: Int = 0,
    @Json(name = "ishp")
    val ishp: Int = 0,
    @Json(name = "keywords")
    val keywords: String = "",
    @Json(name = "last_comment_update")
    val lastCommentUpdate: Int = 0,
    @Json(name = "lastupdate")
    val lastupdate: Int = 0,
    @Json(name = "logo")
    val logo: String = "",
    @Json(name = "open_link")
    val openLink: String = "",
    @Json(name = "packageName")
    val packageName: String = "",
    @Json(name = "pubStatusText")
    val pubStatusText: String = "",
    @Json(name = "pubdate")
    val pubdate: Int = 0,
    @Json(name = "_querySearchTime")
    val querySearchTime: Double = 0.0,
    @Json(name = "_queryTotal")
    val queryTotal: Int = 0,
    @Json(name = "_queryViewTotal")
    val queryViewTotal: Int = 0,
    @Json(name = "recommend")
    val recommend: Int = 0,
    @Json(name = "replyCount")
    val replyCount: Int = 0,
    @Json(name = "replynum")
    val replynum: Int = 0,
    @Json(name = "romversion")
    val romversion: String = "",
    @Json(name = "score")
    val score: String = "",
    @Json(name = "score_v10")
    val scoreV10: Double = 0.0,
    @Json(name = "screenList")
    val screenList: List<String> = listOf(),
    @Json(name = "sdkversion")
    val sdkversion: Int = 0,
    @Json(name = "shortTags")
    val shortTags: String = "",
    @Json(name = "shortlabel")
    val shortlabel: String = "",
    @Json(name = "shorttitle")
    val shorttitle: String = "",
    @Json(name = "star")
    val star: Int = 0,
    @Json(name = "status")
    val status: Int = 0,
    @Json(name = "statusText")
    val statusText: String = "",
    @Json(name = "target_id")
    val targetId: String = "",
    @Json(name = "thumbList")
    val thumbList: List<String> = listOf(),
    @Json(name = "title")
    val title: String = "",
    @Json(name = "updateFlag")
    val updateFlag: String = "",
    @Json(name = "url")
    val url: String = "",
    @Json(name = "version")
    val version: String = "",
    @Json(name = "voteCount")
    val voteCount: String = "",
    @Json(name = "votenum")
    val votenum: Int = 0
)