package com.anpe.coolbbsyou.net.model.index

import com.anpe.coolbbsyou.net.model.SourceFeed
import com.anpe.coolbbsyou.net.model.UserAction
import com.anpe.coolbbsyou.net.model.UserInfo
import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

@JsonClass(generateAdapter = true)
data class Data(
    @Json(name = "at_count")
    val atCount: Int = 0,
    @Json(name = "avatarFetchType")
    val avatarFetchType: String = "",
    @Json(name = "block_status")
    val blockStatus: Int = 0,
    @Json(name = "burynum")
    val burynum: Int = 0,
    @Json(name = "canDisallowReply")
    val canDisallowReply: Int = 0,
    @Json(name = "change_count")
    val changeCount: Int = 0,
    @Json(name = "comment_addition")
    val commentAddition: String = "",
    @Json(name = "comment_addition_pic")
    val commentAdditionPic: String = "",
    @Json(name = "comment_bad")
    val commentBad: String = "",
    @Json(name = "comment_bad_pic")
    val commentBadPic: String = "",
    @Json(name = "comment_block_num")
    val commentBlockNum: Int = 0,
    @Json(name = "comment_general")
    val commentGeneral: String = "",
    @Json(name = "comment_general_pic")
    val commentGeneralPic: String = "",
    @Json(name = "comment_good")
    val commentGood: String = "",
    @Json(name = "comment_good_pic")
    val commentGoodPic: String = "",
    @Json(name = "commentnum")
    val commentnum: Int = 0,
    @Json(name = "create_time")
    val createTime: Int = 0,
    @Json(name = "dateline")
    val dateline: Int = 0,
    @Json(name = "device_build")
    val deviceBuild: String = "",
    @Json(name = "device_name")
    val deviceName: String = "",
    @Json(name = "device_rom")
    val deviceRom: String = "",
    @Json(name = "device_title")
    val deviceTitle: String = "",
    @Json(name = "device_title_url")
    val deviceTitleUrl: String = "",
    @Json(name = "disallow_reply")
    val disallowReply: Int = 0,
    @Json(name = "disallow_repost")
    val disallowRepost: Int = 0,
    @Json(name = "dyh_id")
    val dyhId: Int = 0,
    @Json(name = "dyh_name")
    val dyhName: String = "",
    @Json(name = "editor_title")
    val editorTitle: String = "",
    @Json(name = "enableModify")
    val enableModify: Int = 0,
    @Json(name = "entities")
    val entities: List<Entity> = listOf(),
    @Json(name = "entityFixed")
    val entityFixed: Int = 0,
    @Json(name = "entityId")
    val entityId: Int = 0,
    @Json(name = "entityTemplate")
    val entityTemplate: String = "",
    @Json(name = "entityType")
    val entityType: String = "",
    @Json(name = "extraData")
    val extraData: String = "",
    @Json(name = "extraDataArr")
    val extraDataArr: ExtraDataArr = ExtraDataArr(),
    @Json(name = "extra_fromApi")
    val extraFromApi: String = "",
    @Json(name = "extra_info")
    val extraInfo: String = "",
    @Json(name = "extra_key")
    val extraKey: String = "",
    @Json(name = "extra_pic")
    val extraPic: String = "",
    @Json(name = "extra_status")
    val extraStatus: Int = 0,
    @Json(name = "extra_title")
    val extraTitle: String = "",
    @Json(name = "extra_type") // apk
    val extraType: String = "",
    @Json(name = "extra_url")
    val extraUrl: String = "",
    @Json(name = "favnum")
    val favnum: Int = 0,
    @Json(name = "feed_score")
    val feedScore: Int = 0,
    @Json(name = "feedType")
    val feedType: String = "",
    @Json(name = "feedTypeName")
    val feedTypeName: String = "",
    @Json(name = "fetchType")
    val fetchType: String = "",
    @Json(name = "fid")
    val fid: Int = 0,
    @Json(name = "forwardSourceType")
    val forwardSourceType: String = "",
    @Json(name = "forwardid")
    val forwardid: String = "",
    @Json(name = "forwardnum")
    val forwardnum: Int = 0,
    @Json(name = "fromid")
    val fromid: Int = 0,
    @Json(name = "fromname")
    val fromname: String = "",
    @Json(name = "hitnum")
    val hitnum: Int = 0,
    @Json(name = "id")
    val id: Int = 0,
    @Json(name = "include_goods_ids")
    val includeGoodsIds: List<String> = listOf(),
    @Json(name = "info")
    val info: String = "",
    @Json(name = "infoHtml")
    val infoHtml: String = "",
    @Json(name = "is_anonymous")
    val isAnonymous: Int = 0,
    @Json(name = "is_headline")
    val isHeadline: Int = 0,
    @Json(name = "is_hidden")
    val isHidden: Int = 0,
    @Json(name = "is_html_article")
    val isHtmlArticle: Int = 0,
    @Json(name = "is_ks_doc")
    val isKsDoc: Int = 0,
    @Json(name = "isModified")
    val isModified: Int = 0,
    @Json(name = "is_owner")
    val isOwner: Int = 0,
    @Json(name = "is_pre_recommended")
    val isPreRecommended: Int = 0,
    @Json(name = "is_white_feed")
    val isWhiteFeed: Int = 0,
    @Json(name = "issummary")
    val issummary: Int = 0,
    @Json(name = "istag")
    val istag: Int = 0,
    @Json(name = "label")
    val label: String = "",
    @Json(name = "last_change_time")
    val lastChangeTime: Int = 0,
    @Json(name = "lastupdate")
    val lastupdate: Int = 0,
    @Json(name = "likenum")
    val likenum: Int = 0,
    @Json(name = "location")
    val location: String = "",
    @Json(name = "long_location")
    val longLocation: String = "",
    @Json(name = "media_info")
    val mediaInfo: String = "",
    @Json(name = "media_pic")
    val mediaPic: String = "",
    @Json(name = "media_type")
    val mediaType: Int = 0,
    @Json(name = "media_url")
    val mediaUrl: String = "",
    @Json(name = "message")
    val message: String = "",
    @Json(name = "message_cover")
    val messageCover: String = "",
    @Json(name = "message_keywords")
    val messageKeywords: String = "",
    @Json(name = "message_length")
    val messageLength: Int = 0,
    @Json(name = "message_signature")
    val messageSignature: String = "",
    @Json(name = "message_status")
    val messageStatus: Int = 0,
    @Json(name = "message_title")
    val messageTitle: String = "",
    @Json(name = "message_title_md5")
    val messageTitleMd5: String = "",
    @Json(name = "pic")
    val pic: String = "",
    @Json(name = "picArr")
    val picArr: List<String> = listOf(),
    @Json(name = "pickType")
    val pickType: String = "",
    @Json(name = "post_signature")
    val postSignature: String = "",
    @Json(name = "publish_status")
    val publishStatus: Int = 0,
    @Json(name = "question_answer_num")
    val questionAnswerNum: Int = 0,
    @Json(name = "question_follow_num")
    val questionFollowNum: Int = 0,
    @Json(name = "rank_score")
    val rankScore: Int = 0,
    @Json(name = "rating_score")
    val ratingScore: Int = 0,
    @Json(name = "rating_score_old")
    val ratingScoreOld: Int = 0,
    @Json(name = "recent_hot_reply_ids")
    val recentHotReplyIds: String = "",
    @Json(name = "recent_like_list")
    val recentLikeList: String = "",
    @Json(name = "recent_reply_ids")
    val recentReplyIds: String = "",
    @Json(name = "recommend")
    val recommend: Int = 0,
    @Json(name = "related_dyh_ids")
    val relatedDyhIds: String = "",
    @Json(name = "relateddata")
    val relateddata: List<Any> = listOf(),
    @Json(name = "relatednum")
    val relatednum: Int = 0,
    @Json(name = "replyRows")
    val replyRows: List<ReplyRow> = listOf(),
    @Json(name = "replyRowsCount")
    val replyRowsCount: Int = 0,
    @Json(name = "replyRowsMore")
    val replyRowsMore: Int = 0,
    @Json(name = "replynum")
    val replynum: Int = 0,
    @Json(name = "reportnum")
    val reportnum: Int = 0,
    @Json(name = "share_num")
    val shareNum: Int = 0,
    @Json(name = "shareUrl")
    val shareUrl: String = "",
    @Json(name = "show_owner")
    val showOwner: Int = 0,
    @Json(name = "sourceFeed")
    val sourceFeed: SourceFeed? = SourceFeed(),
    @Json(name = "source_id")
    val sourceId: String = "",
    @Json(name = "star")
    val star: Int = 0,
    @Json(name = "status")
    val status: Int = 0,
    @Json(name = "tag_count")
    val tagCount: Int = 0,
    @Json(name = "tags")
    val tags: String = "",
    @Json(name = "tcat")
    val tcat: Int = 0,
    @Json(name = "tid")
    val tid: Long = 0,
    @Json(name = "_tid")
    val _tid: Int? = 0,
    @Json(name = "tinfo")
    val tinfo: String = "",
    @Json(name = "title")
    val title: String = "",
    @Json(name = "tpic")
    val tpic: String = "",
    @Json(name = "ttitle")
    val ttitle: String = "",
    @Json(name = "ttype")
    val ttype: Int = 0,
    @Json(name = "turl")
    val turl: String = "",
    @Json(name = "turlTarget")
    val turlTarget: String = "",
    @Json(name = "type")
    val type: Int = 0,
    @Json(name = "uid")
    val uid: Int = 0,
    @Json(name = "url")
    val url: String? = "",
    @Json(name = "url_count")
    val urlCount: Int = 0,
    @Json(name = "userAction")
    val userAction: UserAction = UserAction(),
    @Json(name = "userAvatar")
    val userAvatar: String = "",
    @Json(name = "userInfo")
    val userInfo: UserInfo = UserInfo(),
    @Json(name = "user_tags")
    val userTags: String = "",
    @Json(name = "username")
    val username: String = "",
    @Json(name = "viewnum")
    val viewnum: Int = 0,
    @Json(name = "vote_score")
    val voteScore: Int = 0
)