package com.anpe.coolbbsyou.net.model.search


import com.anpe.coolbbsyou.net.model.SourceFeed
import com.anpe.coolbbsyou.net.model.UserAction
import com.anpe.coolbbsyou.net.model.UserInfo
import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

@JsonClass(generateAdapter = true)
data class Data(
    @Json(name = "at_count")
    val atCount: String = "",
    @Json(name = "avatarFetchType")
    val avatarFetchType: String = "",
    @Json(name = "block_status")
    val blockStatus: String = "",
    @Json(name = "burynum")
    val burynum: String = "",
    @Json(name = "buy_status")
    val buyStatus: Int = 0,
    @Json(name = "comment_addition")
    val commentAddition: String = "",
    @Json(name = "comment_addition_pic")
    val commentAdditionPic: String = "",
    @Json(name = "comment_bad")
    val commentBad: String = "",
    @Json(name = "comment_bad_pic")
    val commentBadPic: String = "",
    @Json(name = "comment_block_num")
    val commentBlockNum: String = "",
    @Json(name = "comment_general")
    val commentGeneral: String = "",
    @Json(name = "comment_general_pic")
    val commentGeneralPic: String = "",
    @Json(name = "comment_good")
    val commentGood: String = "",
    @Json(name = "comment_good_pic")
    val commentGoodPic: String = "",
    @Json(name = "commentnum")
    val commentnum: String = "",
    @Json(name = "dateline")
    val dateline: String = "",
    @Json(name = "device_build")
    val deviceBuild: String = "",
    @Json(name = "device_name")
    val deviceName: String = "",
    @Json(name = "device_rom")
    val deviceRom: String = "",
    @Json(name = "device_title")
    val deviceTitle: String = "",
    @Json(name = "device_title_url")
    val deviceTitleUrl: String = "",
    @Json(name = "disallow_reply")
    val disallowReply: String = "",
    @Json(name = "dyh_id")
    val dyhId: String = "",
    @Json(name = "dyh_name")
    val dyhName: String = "",
    @Json(name = "enableModify")
    val enableModify: Int = 0,
    @Json(name = "entities")
    val entities: List<Entity> = listOf(),
    @Json(name = "entityId")
    val entityId: String = "",
    @Json(name = "entityTemplate")
    val entityTemplate: String = "",
    @Json(name = "entityType")
    val entityType: String = "",
    @Json(name = "extraData")
    val extraData: String = "",
    @Json(name = "extra_fromApi")
    val extraFromApi: String = "",
    @Json(name = "extra_info")
    val extraInfo: String = "",
    @Json(name = "extra_key")
    val extraKey: String = "",
    @Json(name = "extra_pic")
    val extraPic: String = "",
    @Json(name = "extra_status")
    val extraStatus: String = "",
    @Json(name = "extra_title")
    val extraTitle: String = "",
    @Json(name = "extra_type")
    val extraType: String = "",
    @Json(name = "extra_url")
    val extraUrl: String = "",
    @Json(name = "favnum")
    val favnum: String = "",
    @Json(name = "feedType")
    val feedType: String = "",
    @Json(name = "feedTypeName")
    val feedTypeName: String = "",
    @Json(name = "fetchType")
    val fetchType: String = "",
    @Json(name = "fid")
    val fid: String = "",
    @Json(name = "forwardSourceType")
    val forwardSourceType: String = "",
    @Json(name = "forwardid")
    val forwardid: String = "",
    @Json(name = "forwardnum")
    val forwardnum: String = "",
    @Json(name = "fromid")
    val fromid: String = "",
    @Json(name = "fromname")
    val fromname: String = "",
    @Json(name = "hitnum")
    val hitnum: String = "",
    @Json(name = "id")
    val id: String = "",
    @Json(name = "index_name")
    val indexName: String = "",
    @Json(name = "info")
    val info: String = "",
    @Json(name = "infoHtml")
    val infoHtml: String = "",
    @Json(name = "is_anonymous")
    val isAnonymous: String = "",
    @Json(name = "is_hidden")
    val isHidden: String = "",
    @Json(name = "is_html_article")
    val isHtmlArticle: String = "",
    @Json(name = "isModified")
    val isModified: Int = 0,
    @Json(name = "is_owner")
    val isOwner: Int = 0,
    @Json(name = "is_pre_recommended")
    val isPreRecommended: Int = 0,
    @Json(name = "issummary")
    val issummary: String = "",
    @Json(name = "istag")
    val istag: String = "",
    @Json(name = "label")
    val label: String = "",
    @Json(name = "lastupdate")
    val lastupdate: String = "",
    @Json(name = "likenum")
    val likenum: String = "",
    @Json(name = "location")
    val location: String = "",
    @Json(name = "media_info")
    val mediaInfo: String = "",
    @Json(name = "media_pic")
    val mediaPic: String = "",
    @Json(name = "media_type")
    val mediaType: String = "",
    @Json(name = "media_url")
    val mediaUrl: String = "",
    @Json(name = "message")
    val message: String = "",
    @Json(name = "message_cover")
    val messageCover: String = "",
    @Json(name = "message_keywords")
    val messageKeywords: String = "",
    @Json(name = "message_length")
    val messageLength: String = "",
    @Json(name = "message_signature")
    val messageSignature: String = "",
    @Json(name = "message_status")
    val messageStatus: String = "",
    @Json(name = "message_title")
    val messageTitle: String = "",
    @Json(name = "message_title_md5")
    val messageTitleMd5: String = "",
    @Json(name = "pic")
    val pic: String = "",
    @Json(name = "picArr")
    val picArr: List<String> = listOf(),
    @Json(name = "post_signature")
    val postSignature: String = "",
    @Json(name = "_querySearchTime")
    val querySearchTime: Double = 0.0,
    @Json(name = "_queryTotal")
    val queryTotal: Int = 0,
    @Json(name = "_queryViewTotal")
    val queryViewTotal: Int = 0,
    @Json(name = "question_answer_num")
    val questionAnswerNum: String = "",
    @Json(name = "question_follow_num")
    val questionFollowNum: String = "",
    @Json(name = "rank_score")
    val rankScore: String = "",
    @Json(name = "rating_score")
    val ratingScore: Int = 0,
    @Json(name = "rating_score_old")
    val ratingScoreOld: Int = 0,
    @Json(name = "recent_hot_reply_ids")
    val recentHotReplyIds: String = "",
    @Json(name = "recent_like_list")
    val recentLikeList: String = "",
    @Json(name = "recent_reply_ids")
    val recentReplyIds: String = "",
    @Json(name = "recommend")
    val recommend: String = "",
    @Json(name = "relateddata")
    val relateddata: List<Any> = listOf(),
    @Json(name = "relatednum")
    val relatednum: String = "",
    @Json(name = "replynum")
    val replynum: String = "",
    @Json(name = "reportnum")
    val reportnum: String = "",
    @Json(name = "shareUrl")
    val shareUrl: String = "",
    @Json(name = "show_owner")
    val showOwner: Int = 0,
    @Json(name = "sourceFeed")
    val sourceFeed: SourceFeed? = SourceFeed(),
    @Json(name = "source_id")
    val sourceId: String = "",
    @Json(name = "star")
    val star: Int = 0,
    @Json(name = "status")
    val status: String = "",
    @Json(name = "tag_count")
    val tagCount: String = "",
    @Json(name = "tags")
    val tags: String = "",
    @Json(name = "tcat")
    val tcat: String = "",
    @Json(name = "tid")
    val tid: String = "",
    @Json(name = "tinfo")
    val tinfo: String = "",
    @Json(name = "title")
    val title: String = "",
    @Json(name = "tpic")
    val tpic: String = "",
    @Json(name = "ttitle")
    val ttitle: String = "",
    @Json(name = "ttype")
    val ttype: String = "",
    @Json(name = "turl")
    val turl: String = "",
    @Json(name = "turlTarget")
    val turlTarget: String = "",
    @Json(name = "type")
    val type: String = "",
    @Json(name = "uid")
    val uid: String = "",
    @Json(name = "url")
    val url: String = "",
    @Json(name = "url_count")
    val urlCount: String = "",
    @Json(name = "userAction")
    val userAction: UserAction = UserAction(),
    @Json(name = "userAvatar")
    val userAvatar: String = "",
    @Json(name = "userInfo")
    val userInfo: UserInfo = UserInfo(),
    @Json(name = "user_tags")
    val userTags: String = "",
    @Json(name = "username")
    val username: String = "",
    @Json(name = "viewnum")
    val viewnum: String = "",
    @Json(name = "vote_score")
    val voteScore: String = ""
)