package com.anpe.coolbbsyou.net.model.search

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

@JsonClass(generateAdapter = true)
data class Entity(
    @Json(name = "adminscore")
    val adminscore: String = "",
    @Json(name = "admintype")
    val admintype: String = "",
    @Json(name = "albumnum")
    val albumnum: String = "",
    @Json(name = "apk_alpha_md5")
    val apkAlphaMd5: String = "",
    @Json(name = "apk_beta_md5")
    val apkBetaMd5: String = "",
    @Json(name = "apkRomVersion")
    val apkRomVersion: String = "",
    @Json(name = "apk_sign_md5")
    val apkSignMd5: String = "",
    @Json(name = "apk_sign_sha1")
    val apkSignSha1: String = "",
    @Json(name = "apkTypeName")
    val apkTypeName: String = "",
    @Json(name = "apkTypeUrl")
    val apkTypeUrl: String = "",
    @Json(name = "apkUrl")
    val apkUrl: String = "",
    @Json(name = "apklength")
    val apklength: String = "",
    @Json(name = "apkmd5")
    val apkmd5: String = "",
    @Json(name = "apkname")
    val apkname: String = "",
    @Json(name = "apkname2")
    val apkname2: String = "",
    @Json(name = "apksize")
    val apksize: String = "",
    @Json(name = "apktype")
    val apktype: String = "",
    @Json(name = "apkversioncode")
    val apkversioncode: String = "",
    @Json(name = "apkversionname")
    val apkversionname: String = "",
    @Json(name = "autoupdate")
    val autoupdate: String = "",
    @Json(name = "avatar_cover_status")
    val avatarCoverStatus: String = "",
    @Json(name = "avatarstatus")
    val avatarstatus: String = "",
    @Json(name = "bury")
    val bury: String = "",
    @Json(name = "catDir")
    val catDir: String = "",
    @Json(name = "catName")
    val catName: String = "",
    @Json(name = "catid")
    val catid: String = "",
    @Json(name = "changelog")
    val changelog: String = "",
    @Json(name = "click")
    val click: String = "",
    @Json(name = "color")
    val color: String = "",
    @Json(name = "comment_block_num")
    val commentBlockNum: String = "",
    @Json(name = "commentCount")
    val commentCount: String = "",
    @Json(name = "comment_status")
    val commentStatus: String = "",
    @Json(name = "commentStatusText")
    val commentStatusText: String = "",
    @Json(name = "commentnum")
    val commentnum: String = "",
    @Json(name = "cover")
    val cover: String = "",
    @Json(name = "createdate")
    val createdate: String = "",
    @Json(name = "creatorname")
    val creatorname: String = "",
    @Json(name = "creatoruid")
    val creatoruid: String = "",
    @Json(name = "credit")
    val credit: String = "",
    @Json(name = "description")
    val description: String = "",
    @Json(name = "developermail")
    val developermail: String = "",
    @Json(name = "developername")
    val developername: String = "",
    @Json(name = "developeruid")
    val developeruid: String = "",
    @Json(name = "digest")
    val digest: String = "",
    @Json(name = "digg")
    val digg: String = "",
    @Json(name = "displayUsername")
    val displayUsername: String = "",
    @Json(name = "downCount")
    val downCount: String = "",
    @Json(name = "downnum")
    val downnum: String = "",
    @Json(name = "emailstatus")
    val emailstatus: String = "",
    @Json(name = "entityId")
    val entityId: String = "",
    @Json(name = "entityTemplate")
    val entityTemplate: String = "",
    @Json(name = "entityType")
    val entityType: String = "",
    @Json(name = "experience")
    val experience: String = "",
    @Json(name = "ext_group_ids")
    val extGroupIds: String = "",
    @Json(name = "extraFlag")
    val extraFlag: String = "",
    @Json(name = "fans")
    val fans: String = "",
    @Json(name = "favnum")
    val favnum: String = "",
    @Json(name = "feed")
    val feed: String = "",
    @Json(name = "fetchType")
    val fetchType: String = "",
    @Json(name = "follow")
    val follow: String = "",
    @Json(name = "followCount")
    val followCount: String = "",
    @Json(name = "follownum")
    val follownum: String = "",
    @Json(name = "fromid")
    val fromid: String = "",
    @Json(name = "fromname")
    val fromname: String = "",
    @Json(name = "fromtype")
    val fromtype: String = "",
    @Json(name = "group_id")
    val groupId: String = "",
    @Json(name = "groupexpires")
    val groupexpires: String = "",
    @Json(name = "groupid")
    val groupid: String = "",
    @Json(name = "hitnum")
    val hitnum: String = "",
    @Json(name = "hot_num")
    val hotNum: String = "",
    @Json(name = "hot_num_txt")
    val hotNumTxt: String = "",
    @Json(name = "hotlabel")
    val hotlabel: String = "",
    @Json(name = "id")
    val id: String = "",
    @Json(name = "index_name")
    val indexName: String = "",
    @Json(name = "introduce")
    val introduce: String = "",
    @Json(name = "isDeveloper")
    val isDeveloper: String = "",
    @Json(name = "is_forum_app")
    val isForumApp: String = "",
    @Json(name = "isbiz")
    val isbiz: String = "",
    @Json(name = "iscps")
    val iscps: String = "",
    @Json(name = "ishot")
    val ishot: String = "",
    @Json(name = "ishp")
    val ishp: String = "",
    @Json(name = "isofficial")
    val isofficial: String = "",
    @Json(name = "ispad")
    val ispad: String = "",
    @Json(name = "keywords")
    val keywords: String = "",
    @Json(name = "last_comment_update")
    val lastCommentUpdate: String = "",
    @Json(name = "last_feed_status")
    val lastFeedStatus: String = "",
    @Json(name = "lastupdate")
    val lastupdate: String = "",
    @Json(name = "level")
    val level: String = "",
    @Json(name = "level_detail_url")
    val levelDetailUrl: String = "",
    @Json(name = "level_today_message")
    val levelTodayMessage: String = "",
    @Json(name = "loginip")
    val loginip: String = "",
    @Json(name = "logintime")
    val logintime: String = "",
    @Json(name = "logo")
    val logo: String = "",
    @Json(name = "maxsdkversion")
    val maxsdkversion: String = "",
    @Json(name = "mobilestatus")
    val mobilestatus: String = "",
    @Json(name = "next_level_experience")
    val nextLevelExperience: Int = 0,
    @Json(name = "next_level_percentage")
    val nextLevelPercentage: String = "",
    @Json(name = "open_link")
    val openLink: String = "",
    @Json(name = "packageName")
    val packageName: String = "",
    @Json(name = "price")
    val price: String = "",
    @Json(name = "pubStatusText")
    val pubStatusText: String = "",
    @Json(name = "pubdate")
    val pubdate: String = "",
    @Json(name = "_querySearchTime")
    val querySearchTime: Double,
    @Json(name = "_queryTotal")
    val queryTotal: Int = 0,
    @Json(name = "_queryViewTotal")
    val queryViewTotal: Int = 0,
    @Json(name = "rank_score")
    val rankScore: String = "",
    @Json(name = "realname")
    val realname: String = "",
    @Json(name = "realnamestatus")
    val realnamestatus: String = "",
    @Json(name = "recommend")
    val recommend: String = "",
    @Json(name = "regdate")
    val regdate: String = "",
    @Json(name = "regip")
    val regip: String = "",
    @Json(name = "replyCount")
    val replyCount: String = "",
    @Json(name = "replynum")
    val replynum: String = "",
    @Json(name = "role_ids")
    val roleIds: String = "",
    @Json(name = "romversion")
    val romversion: String = "",
    @Json(name = "score")
    val score: String = "",
    @Json(name = "score_v10")
    val scoreV10: String = "",
    @Json(name = "screenList")
    val screenList: List<String>,
    @Json(name = "sdkversion")
    val sdkversion: String = "",
    @Json(name = "share_feed_num")
    val shareFeedNum: String = "",
    @Json(name = "shortTags")
    val shortTags: String = "",
    @Json(name = "shortlabel")
    val shortlabel: String = "",
    @Json(name = "shorttitle")
    val shorttitle: String = "",
    @Json(name = "star")
    val star: String = "",
    @Json(name = "status")
    val status: String = "",
    @Json(name = "statusText")
    val statusText: String = "",
    @Json(name = "subtitle")
    val subtitle: String = "",
    @Json(name = "target_id")
    val targetId: String = "",
    @Json(name = "thumbList")
    val thumbList: List<String>,
    @Json(name = "title")
    val title: String = "",
    @Json(name = "uid")
    val uid: String = "",
    @Json(name = "updateFlag")
    val updateFlag: String = "",
    @Json(name = "updatername")
    val updatername: String = "",
    @Json(name = "updateruid")
    val updateruid: String = "",
    @Json(name = "url")
    val url: String = "",
    @Json(name = "userAvatar")
    val userAvatar: String = "",
    @Json(name = "userBigAvatar")
    val userBigAvatar: String = "",
    @Json(name = "userSmallAvatar")
    val userSmallAvatar: String = "",
    @Json(name = "usergroupid")
    val usergroupid: String = "",
    @Json(name = "username")
    val username: String = "",
    @Json(name = "usernamestatus")
    val usernamestatus: String = "",
    @Json(name = "verify_icon")
    val verifyIcon: String = "",
    @Json(name = "verify_label")
    val verifyLabel: String = "",
    @Json(name = "verify_show_type")
    val verifyShowType: String = "",
    @Json(name = "verify_status")
    val verifyStatus: Int = 0,
    @Json(name = "verify_title")
    val verifyTitle: String = "",
    @Json(name = "version")
    val version: String = "",
    @Json(name = "viewnum")
    val viewnum: String = "",
    @Json(name = "voteCount")
    val voteCount: String = "",
    @Json(name = "votenum")
    val votenum: Int = 0,
    @Json(name = "votescore")
    val votescore: String = "",
    @Json(name = "votescore_v10")
    val votescoreV10: String = "",
    @Json(name = "feednum")
    val feednum: String = "",
    @Json(name = "likenum")
    val likenum: String = "",
)