package com.anpe.coolbbsyou.net.model.space

import com.anpe.coolbbsyou.net.model.UserInfo
import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

@JsonClass(generateAdapter = true)
data class Entity(
    @Json(name = "admintype")
    val admintype: Int = 0,
    @Json(name = "alias_title")
    val aliasTitle: String = "",
    @Json(name = "allow_rating")
    val allowRating: Int = 0,
    @Json(name = "avatar_cover_status")
    val avatarCoverStatus: Int = 0,
    @Json(name = "avatar_plugin_status")
    val avatarPluginStatus: Int = 0,
    @Json(name = "avatarstatus")
    val avatarstatus: Int = 0,
    @Json(name = "block_status")
    val blockStatus: Int = 0,
    @Json(name = "brand_id")
    val brandId: Int = 0,
    @Json(name = "buy_count")
    val buyCount: Int = 0,
    @Json(name = "category_id")
    val categoryId: Int = 0,
    @Json(name = "config_num")
    val configNum: Int = 0,
    @Json(name = "cover")
    val cover: String = "",
    @Json(name = "coverArr")
    val coverArr: List<String> = listOf(),
    @Json(name = "create_time")
    val createTime: Int = 0,
    @Json(name = "create_uid")
    val createUid: Int = 0,
    @Json(name = "description")
    val description: String = "",
    @Json(name = "device_info")
    val deviceInfo: String = "",
    @Json(name = "device_owner_status")
    val deviceOwnerStatus: Int = 0,
    @Json(name = "disallow_headline")
    val disallowHeadline: Int = 0,
    @Json(name = "displayUsername")
    val displayUsername: String = "",
    @Json(name = "entityId")
    val entityId: Int = 0,
    @Json(name = "entityType")
    val entityType: String = "",
    @Json(name = "experience")
    val experience: Int = 0,
    @Json(name = "feed_answer_num")
    val feedAnswerNum: Int = 0,
    @Json(name = "feed_article_num")
    val feedArticleNum: Int = 0,
    @Json(name = "feed_comment_num")
    val feedCommentNum: Int = 0,
    @Json(name = "feed_comment_num_txt")
    val feedCommentNumTxt: String = "",
    @Json(name = "feed_review_num")
    val feedReviewNum: Int = 0,
    @Json(name = "feed_trade_num")
    val feedTradeNum: Int = 0,
    @Json(name = "feed_video_num")
    val feedVideoNum: Int = 0,
    @Json(name = "fetchType")
    val fetchType: String = "",
    @Json(name = "follow_num")
    val followNum: Int = 0,
    @Json(name = "follow_num_txt")
    val followNumTxt: String = "",
    @Json(name = "follow_time")
    val followTime: Int = 0,
    @Json(name = "groupid")
    val groupid: Int = 0,
    @Json(name = "hot_num")
    val hotNum: Int = 0,
    @Json(name = "hot_num_txt")
    val hotNumTxt: String = "",
    @Json(name = "id")
    val id: Int = 0,
    @Json(name = "index_title")
    val indexTitle: String = "",
    @Json(name = "isDeveloper")
    val isDeveloper: Int = 0,
    @Json(name = "is_recommend")
    val isRecommend: Int = 0,
    @Json(name = "last_update")
    val lastUpdate: Int = 0,
    @Json(name = "level")
    val level: Int = 0,
    @Json(name = "level_detail_url")
    val levelDetailUrl: String = "",
    @Json(name = "level_today_message")
    val levelTodayMessage: String = "",
    @Json(name = "link_tag")
    val linkTag: String = "",
    @Json(name = "logintime")
    val logintime: Int = 0,
    @Json(name = "logo")
    val logo: String = "",
    @Json(name = "next_level_experience")
    val nextLevelExperience: Int = 0,
    @Json(name = "next_level_percentage")
    val nextLevelPercentage: String = "",
    @Json(name = "owner_buy_count")
    val ownerBuyCount: Int = 0,
    @Json(name = "owner_rating_total_num")
    val ownerRatingTotalNum: Int = 0,
    @Json(name = "owner_star_1_count")
    val ownerStar1Count: Int = 0,
    @Json(name = "owner_star_2_count")
    val ownerStar2Count: Int = 0,
    @Json(name = "owner_star_3_count")
    val ownerStar3Count: Int = 0,
    @Json(name = "owner_star_4_count")
    val ownerStar4Count: Int = 0,
    @Json(name = "owner_star_5_count")
    val ownerStar5Count: Int = 0,
    @Json(name = "owner_star_average_score")
    val ownerStarAverageScore: Double = 0.0,
    @Json(name = "owner_star_total_count")
    val ownerStarTotalCount: Int = 0,
    @Json(name = "price_currency")
    val priceCurrency: String = "",
    @Json(name = "price_max")
    val priceMax: Float = 0f, // Int
    @Json(name = "price_min")
    val priceMin: Float = 0f, // Int
    @Json(name = "rank_status")
    val rankStatus: Int = 0,
    @Json(name = "rating_average_score")
    val ratingAverageScore: Double = 0.0,
    @Json(name = "rating_average_score_1")
    val ratingAverageScore1: String = "",
    @Json(name = "rating_average_score_10")
    val ratingAverageScore10: String = "",
    @Json(name = "rating_average_score_2")
    val ratingAverageScore2: String = "",
    @Json(name = "rating_average_score_3")
    val ratingAverageScore3: String = "",
    @Json(name = "rating_average_score_4")
    val ratingAverageScore4: String = "",
    @Json(name = "rating_average_score_5")
    val ratingAverageScore5: String = "",
    @Json(name = "rating_average_score_6")
    val ratingAverageScore6: String = "",
    @Json(name = "rating_average_score_7")
    val ratingAverageScore7: String = "",
    @Json(name = "rating_average_score_8")
    val ratingAverageScore8: String = "",
    @Json(name = "rating_average_score_9")
    val ratingAverageScore9: String = "",
    @Json(name = "rating_total_num")
    val ratingTotalNum: Int = 0,
    @Json(name = "recent_30_days_star_average_score")
    val recent30DaysStarAverageScore: String = "",
    @Json(name = "recent_30_days_star_total_count")
    val recent30DaysStarTotalCount: Int = 0,
    @Json(name = "recent_7_days_star_average_score")
    val recent7DaysStarAverageScore: String = "",
    @Json(name = "recent_7_days_star_total_count")
    val recent7DaysStarTotalCount: Int = 0,
    @Json(name = "recent_num_star_average_score")
    val recentNumStarAverageScore: String = "",
    @Json(name = "recent_num_star_total_count")
    val recentNumStarTotalCount: Int = 0,
    @Json(name = "recommend_image_num")
    val recommendImageNum: Int = 0,
    @Json(name = "recommend_video_num")
    val recommendVideoNum: Int = 0,
    @Json(name = "regdate")
    val regdate: Int = 0,
    @Json(name = "release_status")
    val releaseStatus: Int = 0,
    @Json(name = "release_time")
    val releaseTime: String = "",
    @Json(name = "sell_url")
    val sellUrl: String = "",
    @Json(name = "series_id")
    val seriesId: Int = 0,
    @Json(name = "share_num")
    val shareNum: Int = 0,
    @Json(name = "short_title")
    val shortTitle: String = "",
    @Json(name = "star_1_count")
    val star1Count: Int = 0,
    @Json(name = "star_2_count")
    val star2Count: Int = 0,
    @Json(name = "star_3_count")
    val star3Count: Int = 0,
    @Json(name = "star_4_count")
    val star4Count: Int = 0,
    @Json(name = "star_5_count")
    val star5Count: Int = 0,
    @Json(name = "star_average_score")
    val starAverageScore: Double = 0.0,
    @Json(name = "star_total_count")
    val starTotalCount: Int = 0,
    @Json(name = "status")
    val status: Int = 0,
    @Json(name = "tagArr")
    val tagArr: List<String> = listOf(),
    @Json(name = "title")
    val title: String = "",
    @Json(name = "type")
    val type: Int = 0,
    @Json(name = "uid")
    val uid: Int = 0,
    @Json(name = "update_time")
    val updateTime: Int = 0,
    @Json(name = "update_uid")
    val updateUid: Int = 0,
    @Json(name = "url")
    val url: String = "",
    @Json(name = "userAvatar")
    val userAvatar: String = "",
    @Json(name = "userBigAvatar")
    val userBigAvatar: String = "",
    @Json(name = "userInfo")
    val userInfo: UserInfo = UserInfo(),
    @Json(name = "userSmallAvatar")
    val userSmallAvatar: String = "",
    @Json(name = "user_type")
    val userType: Int = 0,
    @Json(name = "usergroupid")
    val usergroupid: Int = 0,
    @Json(name = "username")
    val username: String = "",
    @Json(name = "usernamestatus")
    val usernamestatus: Int = 0,
    @Json(name = "verify_icon")
    val verifyIcon: String = "",
    @Json(name = "verify_label")
    val verifyLabel: String = "",
    @Json(name = "verify_show_type")
    val verifyShowType: Int = 0,
    @Json(name = "verify_status")
    val verifyStatus: Int = 0,
    @Json(name = "verify_title")
    val verifyTitle: String = "",
    @Json(name = "vote_bury_num")
    val voteBuryNum: Int = 0,
    @Json(name = "vote_dig_num")
    val voteDigNum: Int = 0,
    @Json(name = "vote_dig_percentage")
    val voteDigPercentage: Int = 0,
    @Json(name = "wish_count")
    val wishCount: Int = 0
)